"""
Django settings for social_help project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w#vq%^4p^b3dl4@6rlxu0wo4ilwk=g@o@q6qha^th!o50g9&)l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'comments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_help.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_help.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

INSTAGRAM_PAGE_ID = "103993782799387"
INSTAGRAM_BUSINESS_ACCOUNT_ID = "17841453019169135"
INSTAGRAM_ACCESS_TOKEN = "EAATgVnZBCYxsBQgYDQlJR9JZBpzpxxQnU7aQcbEqpGI7BAg7gWmdB7404xAZAnORDIW7h5C9a9rifA3ZCEpU43jChEmHEikyBa45ZAjX1bscrIRUNEIQ1XPhr7cAUDM42SNVV1fTXjwzhRDhiWdrgowoW9WFMOepZBlmjgWeDCHxUy1ZBZCS9D5quICqJyR9kxEvS2ocnTmHaQLu"
INSTAGRAM_PAGE_ACCESS_TOKEN  = "EAATgVnZBCYxsBQukw1krKVpZBKlUMaZBjUAxl8gwVvwxj9Dol8IZCWik8umbphxZBnR4SCUW8tuu7CF0mEqnwQ6A6UZC9w95U9CETZBD2QJJNVTOvC0vnhEx0ZB2NYiSbeoMCZCFYfYKsvKWPG5zSNvCPGZAcp5l5Gadb3WoOzmcvddf8LZCetTVptSUVQGz1ZBDVvIEpIJVeMx6HsuRc7IFZCSB8gFxmvQZDZD"