# Generated by Django 4.2.29 on 2026-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_comment_sarcasm_confidence_comment_sarcasm_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationsetting',
            name='enable_sarcasm_detection',
            field=models.BooleanField(default=True, help_text='Enable AI sarcasm detection'),
        ),
        migrations.AddField(
            model_name='moderationsetting',
            name='sarcasm_threshold',
            field=models.FloatField(default=0.5, help_text='Confidence threshold for sarcasm flagging (0.0 - 1.0)'),
        ),
    ]
