# Generated by Django 6.0 on 2025-12-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='decision',
            field=models.CharField(choices=[('delete', 'Delete'), ('keep', 'Keep')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reason',
            field=models.CharField(choices=[('keyword', 'Keyword Match'), ('ai', 'AI Score'), ('clean', 'Clean')], max_length=20),
        ),
    ]
