# Generated by Django 6.0 on 2025-12-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_decision_alter_comment_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toxicity_threshold', models.FloatField(default=0.7)),
                ('keywords', models.TextField(default='stupid,idiot,scam,fake,hate', help_text='Comma separated keywords')),
            ],
        ),
    ]
