# Generated by Django 6.0 on 2026-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_moderationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
