# Generated by Django 4.2.29 on 2026-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_instagram_oauth_auth_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sarcasm_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='sarcasm_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reason',
            field=models.CharField(choices=[('keyword', 'Keyword Match'), ('ai', 'AI Score'), ('clean', 'Clean'), ('toxic_word', 'Toxic Word'), ('positive', 'Positive'), ('spam_keyword', 'Spam Keyword'), ('hf_ai', 'HF AI')], max_length=20),
        ),
    ]
