# Generated by Django 4.2.29 on 2026-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_alter_comment_id_alter_instagramaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='polar_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='polar_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
