# Generated by Django 4.2.29 on 2026-06-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_subscription_polar_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='decision',
            field=models.CharField(choices=[('delete', 'Delete'), ('keep', 'Keep'), ('review', 'Review')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reason',
            field=models.CharField(choices=[('keyword', 'Keyword Match'), ('ai', 'AI Score'), ('clean', 'Clean'), ('toxic_word', 'Toxic Word'), ('positive', 'Positive'), ('spam_keyword', 'Spam Keyword'), ('hf_ai', 'HF Toxicity AI'), ('groq_ai', 'Groq LLM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free Tier (50 comments/mo)'), ('starter', 'Starter ($15/mo - 5,000 comments)'), ('pro', 'Pro ($49/mo - Unlimited & Multi-Account)')], default='free', max_length=20),
        ),
    ]
