# Generated by Django 4.2.29 on 2026-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_alter_comment_decision_alter_comment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reason',
            field=models.CharField(choices=[('keyword', 'Keyword Match'), ('ai', 'AI Score'), ('clean', 'Clean'), ('toxic_word', 'Toxic Word'), ('toxic_phrase', 'Toxic Phrase'), ('positive', 'Positive'), ('spam_keyword', 'Spam Keyword'), ('hf_ai', 'HF Toxicity AI'), ('groq_ai', 'Groq LLM'), ('hf_ai_high_toxicity', 'HF High Toxicity'), ('hf_ai_clean', 'HF Clean'), ('hf_ai_uncertain', 'HF Uncertain'), ('vader_ai_high_toxicity', 'Vader High Toxicity'), ('vader_ai_clean', 'Vader Clean'), ('vader_ai_uncertain', 'Vader Uncertain'), ('fallback_vader_delete', 'Fallback Vader Delete'), ('fallback_vader_keep', 'Fallback Vader Keep')], max_length=255),
        ),
    ]
