# Generated by Django 4.2.29 on 2026-06-20 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0017_alter_comment_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keyword', models.CharField(help_text='Keyword that triggers the auto-reply (case-insensitive)', max_length=100)),
                ('reply_text', models.TextField(help_text='The message or link to reply with')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
