# Generated by Django 4.2.29 on 2026-06-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_autoreplyrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplyrule',
            name='reply_type',
            field=models.CharField(choices=[('public', 'Public Comment'), ('dm', 'Direct Message (DM)')], default='public', help_text='Whether to reply publicly or send a private DM', max_length=10),
        ),
    ]
