# Generated by Django 4.2.29 on 2026-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_autoreplyrule_reply_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly short name (e.g. introducing-socialfuse)', max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in the blog grid')),
                ('content_html', models.TextField(help_text='Full HTML content of the post')),
                ('category', models.CharField(default='All', max_length=100)),
                ('author', models.CharField(default='SocialFuse Team', max_length=100)),
                ('date', models.DateField(help_text='Publication date shown to users')),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('image', models.CharField(default='📝', help_text='Emoji character or icon name for post image', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
