# Generated by Django 4.2.29 on 2026-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0021_make_devesh_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplyrule',
            name='instagram_post_id',
            field=models.CharField(blank=True, help_text='Optional Instagram Post ID or Shortcode. If set, this rule will only trigger on comments of this post.', max_length=100, null=True),
        ),
    ]
