# Generated by Django 4.2.29 on 2026-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0022_autoreplyrule_instagram_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload an image file for the blog post', null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or specify an external image URL', max_length=500, null=True),
        ),
    ]
