# Generated by Django 4.2.29 on 2026-07-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0023_blogpost_image_file_blogpost_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the post (required for Reddit/Quora, optional for others)', max_length=255, null=True)),
                ('content', models.TextField(blank=True, help_text='Main text or caption of the post', null=True)),
                ('post_to_reddit', models.BooleanField(default=False, help_text='Publish to Reddit')),
                ('post_to_quora', models.BooleanField(default=False, help_text='Publish to Quora')),
                ('post_to_linkedin', models.BooleanField(default=False, help_text='Publish to LinkedIn')),
                ('post_to_instagram', models.BooleanField(default=False, help_text='Publish to Instagram')),
                ('post_to_facebook', models.BooleanField(default=False, help_text='Publish to Facebook')),
                ('post_to_twitter', models.BooleanField(default=False, help_text='Publish to Twitter/X')),
                ('media_url', models.URLField(blank=True, help_text='External URL of media (image/video)', max_length=1000, null=True)),
                ('media_file', models.ImageField(blank=True, help_text='Uploaded media file', null=True, upload_to='scheduled_posts/')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Time when the post should be published. If null, it is treated as a draft.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Actual time when publication finished', null=True)),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text="IDs of published posts on each platform, e.g. {'reddit': 't3_abc123'}")),
                ('error_message', models.TextField(blank=True, help_text='Error message if the post publication failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
    ]
