# Generated by Django 4.2.29 on 2026-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0024_scheduledpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationsetting',
            name='live_mode',
            field=models.BooleanField(default=True, help_text='Turn Live Mode On/Off for auto-reply and DMs'),
        ),
    ]
