# Generated by Django 4.2.29 on 2026-09-16 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0027_redditaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(help_text='Meta IG Conversation ID or Thread ID', max_length=100, unique=True)),
                ('participant_id', models.CharField(help_text='Instagram User Scoped ID (IGSID)', max_length=100)),
                ('participant_username', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('participant_profile_pic', models.URLField(blank=True, max_length=1000, null=True)),
                ('last_message_text', models.TextField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='comments.instagramaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or pause this automation rule'),
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last execution', null=True),
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='match_type',
            field=models.CharField(choices=[('contains', 'Contains Keyword'), ('exact', 'Exact Match'), ('ai', 'AI Intent Match')], default='contains', help_text='Keyword matching logic', max_length=20),
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='times_triggered',
            field=models.IntegerField(default=0, help_text='Number of times this rule has fired'),
        ),
        migrations.AddField(
            model_name='autoreplyrule',
            name='trigger_type',
            field=models.CharField(choices=[('comment', 'Instagram Comment'), ('dm', 'Instagram Direct Message (DM)'), ('both', 'Both Comments & DMs')], default='comment', help_text='Where this trigger listens (Comments, DMs, or Both)', max_length=20),
        ),
        migrations.CreateModel(
            name='InstagramDirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Meta IG Message ID (mid.xxx)', max_length=150, unique=True)),
                ('sender_id', models.CharField(help_text='IGSID of message sender', max_length=100)),
                ('sender_username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_from_business', models.BooleanField(default=False, help_text='True if sent by our connected business account')),
                ('text', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_auto_reply', models.BooleanField(default=False, help_text='True if generated by an auto-DM rule')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comments.instagramconversation')),
            ],
            options={
                'ordering': ['timestamp', 'created_at'],
            },
        ),
    ]
