from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import (
    landing,
    react_frontend,
    dashboard,
    signup,
    logout_view,
    instagram_disconnect,
    facebook_oauth_login,
    facebook_oauth_callback,
    instagram_oauth_login,
    instagram_oauth_callback,
    instagram_connect_direct,
    privacy_policy,
    terms_of_service,
    contact,
    pricing_page,
    creators_page,
    brands_page,
    pwa_manifest,
    service_worker,
    android_asset_links,
    gumroad_success,
    gumroad_webhook,
    robots_txt,
    sitemap_xml,
    google_verification,
    serve_root_file,
)

urlpatterns = [
    path("", landing),
    # React frontend pages (client-side routed)
    path("features/", react_frontend),
    path("how-it-works/", react_frontend),
    path("use-cases/", react_frontend),
    path("demo/", react_frontend),
    path("pricing/", react_frontend),
    path("testimonials/", react_frontend),
    path("blog/", react_frontend),
    path("blog/<slug:post_slug>/", react_frontend),
    path("contact/", react_frontend),

    path("robots.txt", robots_txt),
    path("sitemap.xml", sitemap_xml),
    path("google1e281c209d0ab913.html", google_verification),
    re_path(r'^(?P<filename>[a-zA-Z0-9_\-\.]+\.(xml|html|txt))$', serve_root_file),
    path("manifest.webmanifest", pwa_manifest),
    path("sw.js", service_worker),
    path(".well-known/assetlinks.json", android_asset_links),
    path("dashboard/", dashboard),
    path("signup/", signup),
    path("gumroad/success/", gumroad_success),
    path("webhooks/gumroad/", gumroad_webhook),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html")),
    path("logout/", logout_view),
    path("instagram/disconnect/", instagram_disconnect),
    path("instagram/connect/", facebook_oauth_login),
    path("instagram/callback/", facebook_oauth_callback),
    path("instagram/oauth/connect/", instagram_oauth_login),
    path("instagram/oauth/callback/", instagram_oauth_callback),
    path("instagram/connect-direct/", instagram_connect_direct),
    path("privacy-policy/", privacy_policy),
    path("terms-of-service/", terms_of_service),
    path("terms/", terms_of_service),
    path("creators/", creators_page),
    path("brands/", brands_page),
]
