from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    landing,
    react_frontend,
    dashboard,
    signup,
    logout_view,
    instagram_disconnect,
    facebook_oauth_login,
    facebook_oauth_callback,
    instagram_connect_direct,
    privacy_policy,
    terms_of_service,
    contact,
    pricing_page,
    creators_page,
    brands_page,
    pwa_manifest,
    service_worker,
    android_asset_links,
)

urlpatterns = [
    path("", landing),
    # React frontend pages (client-side routed)
    path("features/", react_frontend),
    path("how-it-works/", react_frontend),
    path("use-cases/", react_frontend),
    path("demo/", react_frontend),
    path("pricing/", react_frontend),
    path("testimonials/", react_frontend),
    path("blog/", react_frontend),
    path("contact/", react_frontend),

    path("manifest.webmanifest", pwa_manifest),
    path("sw.js", service_worker),
    path(".well-known/assetlinks.json", android_asset_links),
    path("dashboard/", dashboard),
    path("signup/", signup),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html")),
    path("logout/", logout_view),
    path("instagram/disconnect/", instagram_disconnect),
    path("instagram/connect/", facebook_oauth_login),
    path("instagram/callback/", facebook_oauth_callback),
    path("instagram/connect-direct/", instagram_connect_direct),
    path("privacy-policy/", privacy_policy),
    path("terms-of-service/", terms_of_service),
    path("terms/", terms_of_service),
    path("creators/", creators_page),
    path("brands/", brands_page),
]
